import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useEffect, useState } from 'react'
import axios, { isCancel, AxiosError } from 'axios'
import Modal from '../components/Modal'
import PinInput from 'react-pin-input'
import cookie from 'cookie'
import { NextRequest, NextResponse } from 'next/server'
import logo from '@/asset/images/logo.png'
import g10 from '@/asset/images/g10.png'
import home from '@/asset/images/home.png'



const inter = Inter({ subsets: ['latin'] })
export default function Home() {

    const [tabActive, setTabActive] = useState(1);
    const [tabContentActive, setTabContentActive] = useState('admin');
    const [post, setPost] = useState({ email: "", phone: "" });
    const [email, setEmail] = useState({ email: "" });
    const [showModal, setShowModal] = useState(false);
    const [showerrorModal, setShowerrorModal] = useState(false);
    const [otp, setOtp] = useState({});
    const [token, setToken] = useState({});

    const handleTog = (nu: any, st: any) => {
        setTabActive(nu);
        setTabContentActive(st);
        //console.log(city)
    }

    const handleChange = (event: any) => {
        setEmail(event.target.value);

        // setPost({
        //    ...post,
        //   [event.target.name]: event.target.value
        // });

    }
    const verifyOtp = (event: any) => {
        event.preventDefault();
        verifyOtpsent();
        // onClose();
    }
    const verifyOtpsent = async (req: any, res: any) => {
        try {
            let data = JSON.stringify({
                "email": email,
                "otp": otp
            });
            let config = {
                method: 'put',
                maxBodyLength: Infinity,
                url: 'http://localhost:1112/verifyOTP?=',
                headers: {
                    'Content-Type': 'application/json'
                },
                data: data
            };
            axios(config)
                .then(function (response) {
                    setShowModal(true);
                    setToken(response.data.token);
                    console.log(JSON.stringify(response.data));
                    if (response.data.token) {
                        cookie.set("token", response.data.token);

                    }
                })
                .catch(function (error) {

                    console.log(error);
                });
        } catch (err) {
            console.log(err);
        }
    }

    const sendOtp = async () => {
        try {
            let data = JSON.stringify({
                "email": email
            });
            let config = {
                method: 'put',
                maxBodyLength: Infinity,
                url: 'http://localhost:1112/sendOTP',
                headers: {
                    'Content-Type': 'application/json'
                },
                data: data
            };

            axios(config)
                .then(function (response) {
                    setShowModal(true);
                    console.log(JSON.stringify(response.data));
                    var res_data = JSON.stringify(response.data)
                })
                .catch(function (error) {
                    setShowerrorModal(true);
                    console.log(error);
                });
        } catch (err) {
            console.log(err);
        }

    }

    const handleSubmit = (event: any) => {
        event.preventDefault();
        // setShowModal(true)
        sendOtp();
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                {/* <link rel="stylesheet" href="../public/css/app.css" />
                <link rel="stylesheet" href="../public/css/index.css" /> */}
            </Head>
            <style jsx>{`
      .nav.nav-tabs {
            border-bottom-width: 0px !important;
            border: none !important;
            box-shadow: 0px 4px 5px #ededed;
        }
          .or_ {
            text-align: center;
          }
          .cst_c{
            z-index: 999;
          }
          .active {
              background-color: #031430;
              color: #fff;
          }
          .tin_img{
              width: 170px;
              margin: auto;
          }
          .pincode-input-container .pincode-input-text{
            border: none !important;
            background-color: #ededed;
            width: 50px;
            height: 50px;
          }

          .form-control.cst_con{
            border-color: #ebebeb !important;
            background-color: #fffcfc !important;
          }

          .form-control.cst_con:focus {
              --tw-ring-opacity: 0 !important;
          }
          input.pincode-input-text{
            color: #000 !important;
          }
          .pincode-input-text{
              border: none !important;
              background-color: #ebebeb !important;
          }
        `}</style>
            <div className="container sm:px-10">
                <div className="block xl:grid grid-cols-2 gap-4">
                    <div className="hidden xl:flex flex-col min-h-screen">
                        <a href="" className="-intro-x flex items-center pt-5">
                            <Image src={logo} width="100" alt="logo" height="52" />
                        </a>
                        <div className="my-auto mt-3" style={{ zIndex: 999 }}>
                            <Image src={home} width="300" alt="logo" height="250" />
                            <div className="-intro-x text-white font-medium text-4xl leading-tight mt-10">Get more things done with
                                <br /> Edfish platform.
                            </div>
                            <div className="-intro-x mt-5 text-lg text-white text-opacity-70 dark:text-gray-500">The Complete Ecosystem
                                of Education</div>
                        </div>
                    </div>
                    <div className="h-screen xl:h-auto flex py-5 xl:py-0 my-10 xl:my-0">
                        <div className="my-auto mx-auto xl:ml-20 bg-white dark:bg-dark-1 xl:bg-transparent px-5 sm:px-8 py-8 xl:p-0 rounded-md shadow-md xl:shadow-none w-full sm:w-3/4 lg:w-2/4 xl:w-auto">
                            <div className="intro-y flex justify-center mt-0">
                                <div className="pricing-tabs nav nav-tabs rounded-full overflow-hidden" role="tablist">
                                    <button id="admin" className={`flex-1 w-32 lg:w-40 py-2 lg:py-3 whitespace-nowrap text-center text-black ${tabActive == 1 ? 'active' : ' '}`} role="tab" onClick={() => handleTog(1, 'admin')} >Admin</button>
                                    <button id="staff" className={`flex-1 w-32 lg:w-40 py-2 lg:py-3 whitespace-nowrap text-center text-black ${tabActive == 2 ? 'active' : ' '} `} role="tab" onClick={() => handleTog(2, 'staff')}>Staff</button>
                                    <button id="parent" className={`flex-1 w-32 lg:w-40 py-2 lg:py-3 whitespace-nowrap text-center text-black ${tabActive == 3 ? 'active' : ' '} `} role="tab" onClick={() => handleTog(3, 'parent')}>Parent</button>
                                </div>
                            </div>

                            <div className="tab-content mt-10">
                                <div id="layout-admin" hidden={tabContentActive === 'admin' ? false : true}>
                                    <h2 className="intro-x font-bold text-2xl xl:text-3xl text-center text-black xl:text-left">Admin Sign In</h2>
                                    <div className="intro-x mt-2 text-gray-500 xl:hidden text-center">Get more things done with Edfish platform. The Complete Ecosystem of Education</div>
                                    <div className="intro-x mt-8">
                                        <form >
                                            <input onChange={(event) => handleChange(event)} id="phone" type="text" className="intro-x adminlogin__input form-control cst_con py-3 px-4 border-gray-300 block" placeholder="Phone" />
                                            <br />
                                            <h6 className='or_ text-black'>OR</h6>

                                            <br />
                                            <input onChange={(event) => handleChange(event)} id="email" type="email" className="intro-x adminlogin__input form-control cst_con py-3 px-4 border-gray-300 block" placeholder="email" />
                                        </form>
                                    </div>
                                    <div className="intro-x mt-5 xl:mt-8 text-center xl:text-center">
                                        <button onClick={(event) => handleSubmit(event)} className="btn btn-primary color text-white py-3 px-4 w-full btn-lg lg:w-2 xl:mr-3 align-top text-center">Login</button>
                                    </div>
                                </div>

                                <div id="layout-admin" hidden={tabContentActive === 'staff' ? false : true} >
                                    <h2 className="intro-x font-bold text-2xl xl:text-3xl text-center text-black xl:text-left">Staff Sign In</h2>
                                    <div className="intro-x mt-2 text-gray-500 xl:hidden text-center">Get more things done with Edfish platform. The Complete Ecosystem of Education</div>
                                    <div className="intro-x mt-8">
                                        <form>
                                            <input onChange={(event) => handleChange(event)} id="phone" type="text" className="intro-x adminlogin__input form-control cst_con py-3 px-4 border-gray-300 block" placeholder="Phone" />
                                            <br />
                                            <h6 className='or_ text-black'>OR</h6>

                                            <br />
                                            <input onChange={(event) => handleChange(event)} id="email" type="email" className="intro-x adminlogin__input form-control cst_con py-3 px-4 border-gray-300 block" placeholder="email" />
                                        </form>
                                    </div>
                                    <div className="intro-x mt-5 xl:mt-8 text-center xl:text-center">
                                        <button onClick={(event) => handleSubmit(event)} className="btn btn-primary btn-lg color text-white px-6 px-4 w-full lg:w-2 xl:mr-3 align-top text-center">Login</button>
                                    </div>
                                </div>

                                <div id="layout-admin" hidden={tabContentActive === 'parent' ? false : true} >
                                    <h2 className="intro-x font-bold text-2xl xl:text-3xl text-center text-black xl:text-left">Parent Sign In</h2>
                                    <div className="intro-x mt-2 text-gray-500 xl:hidden text-center">Get more things done with Edfish platform. The Complete Ecosystem of Education</div>
                                    <div className="intro-x mt-8">
                                        <form>
                                            <input onChange={(event) => handleChange(event)} id="phone" type="text" className="intro-x adminlogin__input form-control cst_con py-3 px-4 border-gray-300 block" placeholder="Phone" />
                                            <br />
                                            <h6 className='or_ text-black'>OR</h6>

                                            <br />
                                            <input onChange={(event) => handleChange(event)} id="email" type="email" className="intro-x adminlogin__input form-control cst_con py-3 px-4 border-gray-300 block" placeholder="email" />
                                        </form>
                                    </div>
                                    <div className="intro-x mt-5 xl:mt-8 text-center xl:text-center">
                                        <button onClick={(event) => handleSubmit(event)} className="btn btn-primary rounded-lg color text-white w-full btn-lg lg:w-2 xl:mr-3 align-top text-center">Login</button>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <Modal onClose={() => setShowModal(false)} show={showModal} >
                <div className='text-center'>
                    <h2 className="font-medium text-2xl mx-auto text-black">Enter Your Verification Code</h2>
                    <small className='text-black'>We sent the verification code to xxxxxxxxxx</small>
                    <Image src={g10} alt="logo" className="tin_img pt-4" />
                    <PinInput
                        length={6}
                        initialValue=""
                        onChange={(value, index) => { setOtp(value) }}
                        type="numeric"
                        inputMode="number"
                        style={{ padding: '10px', borderColor: '#F3F5F6' }}
                        inputStyle={{ borderColor: '#F3F5F6', backgroundColor: '#F3F5F6', width: '40px', borderRadius: '3px' }}
                        inputFocusStyle={{ borderColor: '#F3F5F6' }}
                        onComplete={(value, index) => { }}
                        autoSelect={true}
                        regexCriteria={/^[ A-Za-z0-9_@./#&+-]*$/}

                    />
                    <div className="px-5">
                        <button onClick={(event) => verifyOtp(event)} className="btn btn-primary btn-sm px-5 mt-5 mb-1 rounded-lg text-center font-semibold mr-1 text-white sm:w-40" >Submit</button>
                    </div>
                    <small className='text-black'>Not received yet? Resend</small>
                </div>
            </Modal>

        </>
    )
}
